### ISSUE TITLE
编译.cu文件时遇到问题

### ISSUE THREAD

**Issue by treestreamymw** [fangwei123456/Spike-Element-Wise-ResNet#16]
E:\NVIDIACUDA\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\hp\Desktop\spikingjelly\build\temp.win-amd64-cpython-38\Release\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_backward_kernel.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\TH -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\THC -IE:\NVIDIACUDA\CUDA\include -IC:\Users\hp\anaconda3\envs\torch1.12\include -IC:\Users\hp\anaconda3\envs\torch1.12\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c C:\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_backward_kernel.cu -o C:\Users\hp\Desktop\spikingjelly\build\temp.win-amd64-cpython-38\Release\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_backward_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C_neuron -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
FAILED: C:/Users/hp/Desktop/spikingjelly/build/temp.win-amd64-cpython-38/Release/Users/hp/Desktop/spikingjelly/spikingjelly/cext/csrc/neuron/neuron_backward_kernel.obj
E:\NVIDIACUDA\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\hp\Desktop\spikingjelly\build\temp.win-amd64-cpython-38\Release\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_backward_kernel.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\TH -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\THC -IE:\NVIDIACUDA\CUDA\include -IC:\Users\hp\anaconda3\envs\torch1.12\include -IC:\Users\hp\anaconda3\envs\torch1.12\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c C:\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_backward_kernel.cu -o C:\Users\hp\Desktop\spikingjelly\build\temp.win-amd64-cpython-38\Release\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_backward_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C_neuron -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
C:/Users/hp/anaconda3/envs/torch1.12/lib/site-packages/torch/include\c10/macros/Macros.h(143): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
c:\users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: “HAVE_SNPRINTF”: 宏重定义
c:\users\hp\anaconda3\envs\torch1.12\include\pyerrors.h(315): note: 参见“HAVE_SNPRINTF”的前一个定义
C:/Users/hp/anaconda3/envs/torch1.12/lib/site-packages/torch/include\c10/macros/Macros.h(143): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
c:\users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: “HAVE_SNPRINTF”: 宏重定义
c:\users\hp\anaconda3\envs\torch1.12\include\pyerrors.h(315): note: 参见“HAVE_SNPRINTF”的前一个定义
E:/NVIDIACUDA/CUDA/include\thrust/detail/config/cpp_dialect.h:118: warning: Thrust requires at least MSVC 2019 (19.20/16.0/14.20). MSVC 2017 is deprecated but still supported. MSVC 2017 support will be removed in a future release. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
C:/Users/hp/anaconda3/envs/torch1.12/lib/site-packages/torch/include\c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

c:\users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

c:\users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

2 errors detected in the compilation of "C:/Users/hp/Desktop/spikingjelly/spikingjelly/cext/csrc/neuron/neuron_backward_kernel.cu".
neuron_backward_kernel.cu
[3/3] E:\NVIDIACUDA\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\hp\Desktop\spikingjelly\build\temp.win-amd64-cpython-38\Release\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_forward_kernel.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\TH -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\THC -IE:\NVIDIACUDA\CUDA\include -IC:\Users\hp\anaconda3\envs\torch1.12\include -IC:\Users\hp\anaconda3\envs\torch1.12\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c C:\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_forward_kernel.cu -o C:\Users\hp\Desktop\spikingjelly\build\temp.win-amd64-cpython-38\Release\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_forward_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C_neuron -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
FAILED: C:/Users/hp/Desktop/spikingjelly/build/temp.win-amd64-cpython-38/Release/Users/hp/Desktop/spikingjelly/spikingjelly/cext/csrc/neuron/neuron_forward_kernel.obj
E:\NVIDIACUDA\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\hp\Desktop\spikingjelly\build\temp.win-amd64-cpython-38\Release\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_forward_kernel.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\TH -IC:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\THC -IE:\NVIDIACUDA\CUDA\include -IC:\Users\hp\anaconda3\envs\torch1.12\include -IC:\Users\hp\anaconda3\envs\torch1.12\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c C:\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_forward_kernel.cu -o C:\Users\hp\Desktop\spikingjelly\build\temp.win-amd64-cpython-38\Release\Users\hp\Desktop\spikingjelly\spikingjelly\cext\csrc\neuron\neuron_forward_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C_neuron -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
C:/Users/hp/anaconda3/envs/torch1.12/lib/site-packages/torch/include\c10/macros/Macros.h(143): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
c:\users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: “HAVE_SNPRINTF”: 宏重定义
c:\users\hp\anaconda3\envs\torch1.12\include\pyerrors.h(315): note: 参见“HAVE_SNPRINTF”的前一个定义
C:/Users/hp/anaconda3/envs/torch1.12/lib/site-packages/torch/include\c10/macros/Macros.h(143): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
c:\users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: “HAVE_SNPRINTF”: 宏重定义
c:\users\hp\anaconda3\envs\torch1.12\include\pyerrors.h(315): note: 参见“HAVE_SNPRINTF”的前一个定义
E:/NVIDIACUDA/CUDA/include\thrust/detail/config/cpp_dialect.h:118: warning: Thrust requires at least MSVC 2019 (19.20/16.0/14.20). MSVC 2017 is deprecated but still supported. MSVC 2017 support will be removed in a future release. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
C:/Users/hp/anaconda3/envs/torch1.12/lib/site-packages/torch/include\c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

c:\users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

c:\users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

2 errors detected in the compilation of "C:/Users/hp/Desktop/spikingjelly/spikingjelly/cext/csrc/neuron/neuron_forward_kernel.cu".
neuron_forward_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\setup.py", line 54, in <module>
    setup(
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\utils\cpp_extension.py", line 738, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\utils\cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\hp\anaconda3\envs\torch1.12\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by fangwei123456** [comment]
换linux试试，或者用新版框架的代码 https://github.com/fangwei123456/Spike-Element-Wise-ResNet/blob/main/readme.md#new-implement

**Comment by treestreamymw** [comment]
> 换linux试试，或者用新版框架的代码 https://github.com/fangwei123456/Spike-Element-Wise-ResNet/blob/main/readme.md#new-implement

好的，我试试，谢谢
